[package]
name = "bevy-shader-macros"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.92"


[dev-dependencies]
bevy-shader-helper = { workspace = true }
