[package]
name = "bevy-shazzy-macros"
version = "0.0.1"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
bevy-shazzy-tokens = { workspace = true }

[dev-dependencies]
bevy-shazzy = { workspace = true, features = ["derive"] }
